# Generated by Django 2.2.2 on 2019-07-13 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site_item',
            new_name='Item',
        ),
    ]
