# Generated by Django 2.2.2 on 2019-07-14 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190714_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_publisher',
            new_name='item_published',
        ),
    ]
