# Generated by Django 2.2.2 on 2019-07-14 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190714_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_category', models.CharField(max_length=200, verbose_name='Kategoria')),
                ('category_summary', models.CharField(max_length=200, verbose_name='Opis kategorii')),
                ('category_slug', models.CharField(default=1, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='item_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.CreateModel(
            name='ItemSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_series', models.CharField(max_length=200, verbose_name='Seria')),
                ('series_summary', models.CharField(max_length=200, verbose_name='Opis serii')),
                ('item_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.ItemCategory', verbose_name='Kategoria')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.ItemSeries', verbose_name='Seria'),
        ),
    ]
