# Generated by Django 2.2.2 on 2019-07-14 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190714_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_series',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ItemSeries', verbose_name='Seria'),
        ),
        migrations.AlterField(
            model_name='itemseries',
            name='item_category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ItemCategory', verbose_name='Kategoria'),
        ),
    ]
